version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: exmonapi
      POSTGRES_DB: ex_mon_dev
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data